import { Platform, StyleSheet } from "react-native";
import { C, R, shadow } from "../lib/theme";

export { C as colors, R as radius };

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 100 },

  // ── Header ───────────────────────────────────────────────────────────────────
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 14,
    backgroundColor: C.surface,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  headerGreeting: { fontSize: 13, color: C.textMuted },
  headerTitle: { fontSize: 22, fontWeight: "700", color: C.text, letterSpacing: -0.5 },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: R.pill,
    backgroundColor: C.cyanLight,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 20,
  },

  // ── Logo ─────────────────────────────────────────────────────────────────────
    logoWrap: { alignItems: "center", marginBottom: 48 },
    logoCircle: {
      width: 72,
      height: 72,
      borderRadius: R.pill,
      backgroundColor: C.white,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 16,
      ...Platform.select({
        ios: { shadowColor: C.cyan, shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.35, shadowRadius: 14 },
        android: { elevation: 8 },
      }),
    },
    logoTitle: { fontSize: 28, fontWeight: "800", color: C.text, letterSpacing: -1 },
    logoImage: { width: 50, height: 50 },
    logoSub: { fontSize: 14, color: C.textMuted, marginTop: 4 },
    
  // ── Billing ──────────────────────────────────────────────────────────────────
  billingCard: {
    borderRadius: R.lg,
    backgroundColor: C.cyan,
    padding: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 20,
    ...shadow(3),
  },
  billingLabel: { fontSize: 12, fontWeight: "700", color: "rgba(0,0,0,0.45)", letterSpacing: 0.5 },
  billingValue: { fontSize: 34, fontWeight: "800", color: C.text, letterSpacing: -1, marginTop: 2 },
  billingPeriod: { fontSize: 12, color: "rgba(0,0,0,0.4)", marginTop: 2 },
  billingIcon: {
    width: 52,
    height: 52,
    borderRadius: R.pill,
    backgroundColor: "rgba(255,255,255,0.3)",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Capacidade ───────────────────────────────────────────────────────────────
  capacityCard: {
    backgroundColor: C.surface,
    borderRadius: R.lg,
    padding: 20,
    marginTop: 16,
    ...shadow(2),
  },
  capacityRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  capacityLabel: { fontSize: 15, fontWeight: "600", color: C.text },
  badge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: R.pill },
  badgeText: { fontSize: 12, fontWeight: "700" },
  capacityNumbers: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
    marginBottom: 10,
  },
  capacityCurrent: {
    fontSize: 52,
    fontWeight: "800",
    color: C.text,
    lineHeight: 56,
    letterSpacing: -2,
  },
  capacitySlash: { fontSize: 30, color: C.textMuted, fontWeight: "300" },
  capacityMax: { fontSize: 30, color: C.textMuted, fontWeight: "500" },
  capacitySub: { fontSize: 13, color: C.textSub, marginBottom: 14 },
  track: { height: 8, backgroundColor: C.border, borderRadius: R.pill, overflow: "hidden" },
  fill: { height: "100%", borderRadius: R.pill },
  trackLabels: { flexDirection: "row", justifyContent: "space-between", marginTop: 5 },
  trackLabel: { fontSize: 11, color: C.textMuted },

  // ── Métricas ─────────────────────────────────────────────────────────────────
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 24,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: C.textSub,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  sectionAction: { fontSize: 13, fontWeight: "600", color: C.cyan },
  metricsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  metricCard: {
    flex: 1,
    minWidth: "45%",
    backgroundColor: C.surface,
    borderRadius: R.md,
    padding: 16,
    ...shadow(1),
  },
  metricIcon: {
    width: 36,
    height: 36,
    borderRadius: R.sm,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  metricValue: { fontSize: 28, fontWeight: "800", color: C.text, letterSpacing: -0.5 },
  metricLabel: { fontSize: 12, color: C.textSub, marginTop: 2 },

  // ── Próximas entradas/saídas ──────────────────────────────────────────────────
  eventRow: {
    backgroundColor: C.surface,
    borderRadius: R.md,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
    ...shadow(1),
  },
  eventDot: { width: 10, height: 10, borderRadius: R.pill },
  eventName: { fontSize: 14, fontWeight: "600", color: C.text, flex: 1 },
  eventDate: { fontSize: 12, color: C.textMuted },

  // ── FAB ──────────────────────────────────────────────────────────────────────
  fab: {
    position: "absolute",
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: R.pill,
    backgroundColor: C.cyan,
    alignItems: "center",
    justifyContent: "center",
    ...shadow(3),
  },

  // ── Modal ─────────────────────────────────────────────────────────────────────
  modalContainer: { flex: 1, backgroundColor: C.bg },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: C.surface,
    borderBottomWidth: 1,
    borderBottomColor: C.border,
  },
  modalTitle: { fontSize: 17, fontWeight: "700", color: C.text },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: R.pill,
    backgroundColor: C.surfaceAlt,
    alignItems: "center",
    justifyContent: "center",
  },
  modalSaveBtn: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: C.cyan,
    borderRadius: R.pill,
  },
  modalSaveBtnText: { fontSize: 14, fontWeight: "700", color: C.text },
  modalScroll: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 48 },
  field: { marginBottom: 16 },
  fieldLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: C.textSub,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  input: {
    backgroundColor: C.surface,
    borderWidth: 1.5,
    borderColor: C.border,
    borderRadius: R.md,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: C.text,
  },
  inputFocused: { borderColor: C.cyan },
  chips: { flexDirection: "row", gap: 8, flexWrap: "wrap" },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: R.pill,
    borderWidth: 1.5,
    borderColor: C.border,
    backgroundColor: C.surface,
  },
  chipActive: { backgroundColor: C.cyan, borderColor: C.cyan },
  chipText: { fontSize: 13, fontWeight: "600", color: C.textSub },
  chipTextActive: { color: C.text },

  // ── Vazio ─────────────────────────────────────────────────────────────────────
  empty: { alignItems: "center", paddingVertical: 32, gap: 6 },
  emptyText: { fontSize: 14, color: C.textMuted, fontWeight: "500" },
  emptySub: { fontSize: 12, color: C.textMuted },
});